utils/run-tests.js

fix tests not run in node 0.12

---

lib/main/editor-init.js

make sure profile directory exists

---

lib/main/editor-init.js
lib/renderer/editor-init.js
lib/share/selection.js
lib/share/undo.js
test/main/undo.js

update fireball-x/fireball#459

add basic undo API

---

lib/main/editor-menu.js
lib/renderer/editor-menu.js

update fireball-x/fireball#629

add Editor.Menu.register, Editor.Menu.getMenu

---

lib/main/editor-menu.js
lib/main/main-menu.js
lib/renderer/editor-menu.js
lib/renderer/main-menu.js
test/main/menu.js

update fireball-x/fireball#629

add Editor.Menu.update

---

lib/main/editor-menu.js
lib/renderer/editor-menu.js

update fireball-x/fireball#629

add Editor.Menu.walk

---

lib/renderer/ui/init.js

update fireball-x/fireball#650

fix bindUUID crash

---

CHANGELOG.md
lib/main/editor-init.js
lib/renderer/editor-init.js
lib/share/i18n.js
package.json

update fireball-x/fireball#882

add simple i18n solution

---

docs/editor/packages/i18n.md
docs/index.md
lib/main/editor-package.js
lib/main/index.js
lib/renderer/editor-init.js
lib/renderer/editor-panel.js
lib/share/i18n.js
test/fixtures/packages/localize/i18n/en.js
test/fixtures/packages/localize/i18n/zh.js
test/fixtures/packages/localize/main.js
test/fixtures/packages/localize/package.json
test/fixtures/packages/localize/panel/panel.html
test/main/package.js

update fireball-x/fireball#882

support load and unload i18n from package

---

lib/main/editor-init.js

update fireball-x/fireball#997

send console:clear when clearLog

---

lib/main/editor-panel.js

update fireball-x/fireball#963

use packges:// url for simple window

---

lib/main/editor-init.js
lib/renderer/editor-init.js
lib/share/math.js

update fireball-x/fireball#1060

use Editor.Math

---

lib/share/math.js

update fireball-x/fireball#1032

more math methods

---

lib/main/editor-menu.js
lib/main/main-menu.js
lib/tester/main-menu.js

update fireball-x/fireball#1048

use role instead of selector

---

lib/renderer/audio.js
lib/renderer/editor-init.js

update fireball-x/fireball#1193

add audio preview

---

lib/share/selection.js

make sure selection ipc register after init

---

lib/main/index.js

update fireball-x/fireball#1393

fix close all window will shutdown the programme

---

lib/renderer/ipc-init.js

fix comment

---

lib/renderer/ipc-init.js
test/fixtures/ipc/send2pkg-simple.html
test/main/ipc-reply.js
test/main/ipc.js

update cocos-creator/fireball#1884

add Editor.sendToPackage

---

CHANGELOG.md
docs/packages/create-your-package.md
lib/main/editor-menu.js
lib/main/editor-package.js
package.json
test/fixtures/packages/host-not-exists/package.json
test/fixtures/packages/localize/package.json
test/fixtures/packages/main-deps/package.json
test/fixtures/packages/main-js-broken/package.json
test/fixtures/packages/needs-build/package.json
test/fixtures/packages/package-json-broken/package.json
test/fixtures/packages/simple/package.json

update cocos-creator/fireball#1892

change main menu registry field from menu to main-menu

---

index.js
lib/renderer/editor-panel.js
lib/renderer/index.js
lib/renderer/ui/init.js

update cocos-creator/fireball#833

add panel-copy, panel-cut and panel-paste event when panel focused

---

lib/main/editor-menu.js
lib/main/main-menu.js
lib/share/editor-utils.js
package.json
static/i18n/en.js
static/i18n/zh.js
test/main/ipc-reply.js
utils/run-dev.js

update cocos-creator/fireball#1959

fix main menu reset do not convert the template first

---

lib/renderer/ui/dock/panel/tabs.js
package.json
static/i18n/en.js
static/i18n/zh.js

fixes cocos-creator/fireball#2086

hide unused menu

---

CHANGELOG.md
demo/utils/git-commit.sh
demo/utils/git-pull.sh
demo/utils/git-push.sh
demo/utils/git-status.sh
lib/main/console.js
lib/main/debugger.js
lib/main/ipc.js
lib/main/package.js
lib/main/panel.js
lib/main/profile.js
lib/main/window.js
lib/renderer/editor.js
lib/renderer/ipc.js
lib/renderer/panel.js
lib/renderer/ui/utils/dock-utils.js
lib/share/ipc.js
test/fixtures/ipc/send2main-reply-nested.html
test/fixtures/ipc/send2main-reply-simple-timeout.html
test/fixtures/ipc/send2main-reply-simple.html
test/fixtures/ipc/sendreq2win-nested.html
test/fixtures/ipc/sendreq2win-simple-timeout.html
test/fixtures/ipc/sendreq2win-simple.html
test/fixtures/packages/main-ipc/main.js
test/live/ipc-demo/main.js
test/live/ipc-demo/page.html
test/main/ipc-reply.js
test/main/package.js

update cocos-creator/fireball#2642

add explicit error argument in event.reply

---

CHANGELOG.md
docs/getting-start/app-lifecycle-and-events.md
docs/packages/create-panels.md
docs/packages/create-your-package.md
lib/main/package.js
lib/main/panel.js
lib/renderer/panel-ready.js
lib/renderer/panel.js
static/layout.json
tasks/run-dev.js
tasks/run.js

update cocos-creator/fireball#2118

use run function instead of editor:panel-run message

---

CHANGELOG.md
docs/packages/panel-lifecycle-and-events.md
lib/renderer/ui/panel/panel.js

update cocos-creator/fireball#2118

change resize event to panel-resize event for panel-frame

---

CHANGELOG.md
docs/packages/panel-lifecycle-and-events.md
index.js
lib/main/console.js
lib/renderer/panel.js
lib/renderer/ui/behaviors/dockable.js
renderer.js

update cocos-creator/fireball#2118

add close lifecycle callback

---

lib/main/console.js

Re : https://github.com/cocos-creator/fireball/issues/3240

add clearErrorLog

---

docs/packages/create-panels.md
lib/main/panel.js

support frameless panel

---

index.js
lib/builder/index.js
lib/main/debugger.js
lib/main/ipc.js
lib/main/main-menu.js
lib/main/menu.js
lib/main/package.js
lib/main/panel.js
lib/main/window.js
lib/renderer/ipc.js
lib/renderer/menu.js
lib/renderer/panel-loader.js
lib/renderer/panel.js
lib/renderer/ui/behaviors/focusable.js
lib/renderer/ui/elements/prop.js
lib/renderer/ui/utils/focus-mgr.js
lib/renderer/ui/utils/polymer-utils.js
lib/renderer/ui/utils/resource-mgr.js
lib/share/selection.js
lib/share/undo.js
lib/tester/index.js
lib/tester/renderer/helper.js
lib/tester/share/helper.js
test/live/curve/curve.js
test/renderer/dom-utils.js

Numerous error messages have been improved to make tracing and debugging easier.

Update error messages for several errors to improve clarity.

---

README.md
docs/packages/create-panels.md
docs/packages/create-your-package.md
docs/packages/load-and-build-packages.md

More documentation improvements.

Improved documentation

---

README.md

Update copy in opening paragraph. Better indentation for features section.

More readme.md updates

---

lib/main/editor.js

ignoring watching node_modules in packages

---

docs/packages/create-panels.md

better explaination of panel ID

---

lib/renderer/ui/elements/input.js

将 ui-input 的 type 属性传递给内部的 input 对象。
实现标准 Html 5 上的 password / number / email 等特殊的输入框
https://github.com/cocos-creator/fireball/issues/3950

ui-input 增加一个 type 属性
